In [2]:
**The Data Kitchen & The Data Chef
# Intuition
# Data from an American company
# The data contains the height and weightof patientd admitted in the hospital
# Three columns: Height, Weight, Time of Record
# Height: 6.2, 5,4, 5.8 (ft) (Meters)
# weight: 190, 230, 120 (Pounds) (kg)
# Time: 13:56, 4:08, 7:10
# Analyze this data for the Nigerian system

SyntaxError: invalid syntax (3317204536.py, line 1)

In [ ]:
# Dataset of Interest
# Nigerian Economic Data
# Nigerian Nursing Mothers Healthcare Data
# Nigerian UNemployment Data

In [3]:
# Package of Interest
import pandas as pd

In [4]:
# Inspection of Unemployment Data
unemployment_data = pd.read_csv('/kaggle/input/datasets/awofiranyejames/unemployment-dataset/nigeria_unemployment_missing_data.csv')
unemployment_data.head()

,Age,Gender,Region,Location,Education_Level,Employment_Status,Years_Of_Experience,Monthly_Income_NGN
0,53,Male,North West,Urban,NaN,Employed,37.0,84220.84
1,43,Female,South West,Urban,Primary,Employed,24.0,69911.72
2,29,Female,South South,Rural,NaN,Underemployed,NaN,31096.21
3,57,Female,South West,Rural,Primary,Employed,42.0,108994.91
4,22,Female,South South,Rural,NaN,Underemployed,5.0,31807.56

In [5]:
# Inspect the ingredients
# You are looking for rot (Missing values)
# Why are you looking out for rot (Missing Values)?
# Find out how many blank spaces are in your data
unemployment_data.isnull().sum()

Age                       0
Gender                    0
Region                  250
Location                  0
Education_Level        1127
Employment_Status         0
Years_Of_Experience     500
Monthly_Income_NGN      408
dtype: int64

In [6]:
# What are the implications for the missing values?
unemployment_data.shape

(5000, 8)

In [7]:
# We must approach wrangling with several assumption
# 1. We may not need the missing values
# 2. We must understand why the missing value exist
# 3. We must have contingencies for dealing with missing data

In [9]:
# We may not need the missing values
unemployment_data_1 = unemployment_data.copy()

In [10]:
unemployment_data_1.head()

,Age,Gender,Region,Location,Education_Level,Employment_Status,Years_Of_Experience,Monthly_Income_NGN
0,53,Male,North West,Urban,NaN,Employed,37.0,84220.84
1,43,Female,South West,Urban,Primary,Employed,24.0,69911.72
2,29,Female,South South,Rural,NaN,Underemployed,NaN,31096.21
3,57,Female,South West,Rural,Primary,Employed,42.0,108994.91
4,22,Female,South South,Rural,NaN,Underemployed,5.0,31807.56

In [12]:
# Take away all the missing values
unemployment_data_1.dropna(inplace=True)

In [13]:
unemployment_data.shape

(5000, 8)

In [14]:
# Dataframe without missing value
unemployment_data_1.shape

(3018, 8)

In [15]:
# Fix the years of experience column
# We think "Years of Experience" is subjective
# We will fill the missing values with the average years of experience
# Calculate the average years of experience
average_experience = unemployment_data['Years_Of_Experience'].mean()

In [16]:
average_experience

np.float64(21.835333333333335)

In [17]:
# Before we fix the column with missing values
unemployment_data_avg_years = unemployment_data.copy()

In [18]:
# The Years of Experience has been filled with the average years of experience
unemployment_data_avg_years['Years_Of_Experience'].fillna(average_experience, inplace=True)

/tmp/ipykernel_58/3659221784.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unemployment_data_avg_years['Years_Of_Experience'].fillna(average_experience, inplace=True)

In [19]:
unemployment_data_avg_years.isnull().sum()

Age                       0
Gender                    0
Region                  250
Location                  0
Education_Level        1127
Employment_Status         0
Years_Of_Experience       0
Monthly_Income_NGN      408
dtype: int64

In [20]:
# Tracking Education_Level in Unemployment Data (Average Years)
unemployment_data_avg_years.Education_Level.value_counts(normalize=True)

Education_Level
Secondary    0.455203
Primary      0.312419
Tertiary     0.232378
Name: proportion, dtype: float64

In [21]:
unemployment_data_avg_years['Education_Level'] = unemployment_data_avg_years['Education_Level'].replace(float('nan'), None)
print(unemployment_data_avg_years['Education_Level'].isnull().sum()) # Should be 0 now

unemployment_data_avg_years['Education_Level'].head()

1127

0       None
1    Primary
2       None
3    Primary
4       None
Name: Education_Level, dtype: object

In [22]:
unemployment_data_avg_years.Education_Level.value_counts()

Education_Level
Secondary    1763
Primary      1210
Tertiary      900
Name: count, dtype: int64

In [23]:
unemployment_data_avg_years['Education_Level'] = unemployment_data_avg_years['Education_Level'].fillna('Unknown')
unemployment_data_avg_years['Education_Level'].value_counts()

Education_Level
Secondary    1763
Primary      1210
Unknown      1127
Tertiary      900
Name: count, dtype: int64

In [28]:
unemployment_data_avg_years['Education_Level'].value_counts(normalize=True)

Education_Level
Secondary    0.3526
Primary      0.2420
Unknown      0.2254
Tertiary     0.1800
Name: proportion, dtype: float64